#
# ---- Base Node ----
FROM node:18.12.1-slim AS base
# set working directory
WORKDIR /app
# copy project file
COPY . ./
 
#
# ---- Dependencies ----
FROM base AS dependencies
# install node packages
RUN npm config set legacy-peer-deps true
RUN npm set progress=false && npm config set depth 0
RUN npm install
 
#
# ---- Test ----
# run linters, setup and tests
FROM dependencies AS test
COPY . .
RUN  npm run lint && npm run test
 
#
# ---- Release ----
FROM base AS release
# copy development node_modules
COPY --from=dependencies /app/node_modules ./node_modules
# expose port and define CMD
EXPOSE 3000
CMD npm run dev